### PR TITLE
Restruct

### PR DESCRIPTION
**Pull request by mirceaulinic**

### CODE REVIEW

**Comment by 0xf10e** [comment]
You know it's bad style to merge your own changes in a shared repository, right?

**Comment by mirceaulinic** [comment]
Hi @0xf10e thanks for information. No, I wasn't aware of this -- could you please let me know who should I ping when I have some changes ready to be merged?

**Comment by javierbertoli** [comment]
@mirceaulinic, you should submit a PR (usually from a fork in your own GH account), and all the subscribed to the repo will be emailed about it. Eventually, you might request a reviewer if you know someone is particularly interested in this formula.

**Comment by mirceaulinic** [comment]
Thanks, @javierbertoli - I keep that in mind from now on.

**Pull request merged**
