### PR TITLE
Upgrade napalm libs on state run

### PR DESCRIPTION
**Pull request by mirceaulinic**

### CODE REVIEW

**Comment by wasabi222** [comment]
Is it better to set either a requisite or a feature-toggle for the `upgrade: true` portion of that pip state? Personally I like pinning to a specific version of a driver in case an upgrade breaks anything, but it looks as though it would try to upgrade on each state run if this were set on a schedule, which may not be ideal. What do you think @mirceaulinic ?

**Comment by mirceaulinic** [comment]
Thanks for suggestion @wasabi222 - that's a good point.
How about the following: we should allow setting a certain version, e.g.:

```yaml
napalm:
  - napalm-junos: 0.12.0
  - napalm-iosxr: 0.100.0
  - napalm-ios
```

If there's no specific version configured, upgrade to the latest available.
How would you find that?

**Comment by wasabi222** [comment]
:+1:

**Comment by mirceaulinic** [comment]
Closing as this **finally** will be implemented via #11.

**Pull request closed without merging**
